// ─── CATEGORY DATA ───────────────────────────────────────────────────────────
export const CATEGORIES = [
  {
    id: 'restaurants',
    name: 'Restaurants',
    eyebrow: 'Top Ten',
    subtitle: 'Explore the highest-rated restaurants, carefully curated and ranked worldwide.',
    accentColor: '#c9a84c',
    lightColor: '#ffd080',
    object: 'burger',
    rankings: [
      { name: 'Noma', location: 'Copenhagen, Denmark' },
      { name: 'El Celler de Can Roca', location: 'Girona, Spain' },
      { name: 'Osteria Francescana', location: 'Modena, Italy' },
      { name: 'Mirazur', location: 'Menton, France' },
      { name: 'Central', location: 'Lima, Peru' },
    ],
  },
  {
    id: 'hotels',
    name: 'Hotels',
    eyebrow: 'Top Ten',
    subtitle: 'Discover exceptional hospitality, luxury stays and unforgettable experiences.',
    accentColor: '#a8c4e0',
    lightColor: '#6090c0',
    object: 'hotel',
    rankings: [
      { name: 'Aman Tokyo', location: 'Tokyo, Japan' },
      { name: 'The Brando', location: 'French Polynesia' },
      { name: 'Singita Grumeti', location: 'Serengeti, Tanzania' },
      { name: 'Four Seasons Bali', location: 'Bali, Indonesia' },
      { name: 'Rosewood Hong Kong', location: 'Hong Kong' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports Centers',
    eyebrow: 'Top Ten',
    subtitle: 'Find the finest sports clubs, fitness centers and athletic facilities.',
    accentColor: '#7ab87a',
    lightColor: '#50c050',
    object: 'ball',
    rankings: [
      { name: 'David Lloyd Meridian', location: 'London, UK' },
      { name: 'Equinox Hudson Yards', location: 'New York, USA' },
      { name: 'Technogym Village', location: 'Cesena, Italy' },
      { name: 'Third Space', location: 'London, UK' },
      { name: 'Chelsea Piers', location: 'New York, USA' },
    ],
  },
  {
    id: 'cafes',
    name: 'Cafes',
    eyebrow: 'Top Ten',
    subtitle: "The world's most iconic cafes, from Viennese classics to third-wave innovators.",
    accentColor: '#d4956a',
    lightColor: '#c07040',
    object: 'cup',
    rankings: [
      { name: 'Café Central', location: 'Vienna, Austria' },
      { name: 'Blue Bottle Ferry', location: 'San Francisco, USA' },
      { name: 'Tim Wendelboe', location: 'Oslo, Norway' },
      { name: 'Workshop Coffee', location: 'London, UK' },
      { name: 'Onibus Coffee', location: 'Tokyo, Japan' },
    ],
  },
  {
    id: 'cars',
    name: 'Car Dealers',
    eyebrow: 'Top Ten',
    subtitle: 'Elite automotive destinations offering the pinnacle of vehicular luxury.',
    accentColor: '#e0e0e8',
    lightColor: '#a0b0d0',
    object: 'car',
    rankings: [
      { name: 'Bentley London', location: 'London, UK' },
      { name: 'Ferrari Maranello', location: 'Maranello, Italy' },
      { name: 'Rolls-Royce Munich', location: 'Munich, Germany' },
      { name: 'McLaren Beverly Hills', location: 'Los Angeles, USA' },
      { name: 'Porsche Zuffenhausen', location: 'Stuttgart, Germany' },
    ],
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    eyebrow: 'Top Ten',
    subtitle: 'The most prestigious properties and agencies redefining residential luxury.',
    accentColor: '#b8a4d4',
    lightColor: '#8060c0',
    object: 'house',
    rankings: [
      { name: 'Knight Frank', location: 'Global' },
      { name: "Sotheby's International", location: 'Global' },
      { name: "Christie's Real Estate", location: 'Global' },
      { name: 'Savills Prime', location: 'London, UK' },
      { name: 'Douglas Elliman', location: 'New York, USA' },
    ],
  },
  {
    id: 'travel',
    name: 'Travel Agencies',
    eyebrow: 'Top Ten',
    subtitle: 'Curated journeys and bespoke adventures crafted for the discerning traveller.',
    accentColor: '#7ab8b8',
    lightColor: '#40a0a8',
    object: 'airplane',
    rankings: [
      { name: 'Abercrombie & Kent', location: 'Global' },
      { name: 'Tauck World Discovery', location: 'Global' },
      { name: 'Scott Dunn', location: 'London, UK' },
      { name: 'Butterfield & Robinson', location: 'Toronto, Canada' },
      { name: 'Wilderness Safaris', location: 'Africa' },
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping Centers',
    eyebrow: 'Top Ten',
    subtitle: "The world's most extraordinary retail destinations and luxury shopping experiences.",
    accentColor: '#e8b4c4',
    lightColor: '#d070a0',
    object: 'diamond',
    rankings: [
      { name: 'Harrods', location: 'London, UK' },
      { name: 'Galeries Lafayette', location: 'Paris, France' },
      { name: 'The Dubai Mall', location: 'Dubai, UAE' },
      { name: 'Ginza Six', location: 'Tokyo, Japan' },
      { name: 'Saks Fifth Avenue', location: 'New York, USA' },
    ],
  },
]
